kind: pipeline
type: docker
name: test-secret

platform:
  os: linux
  arch: amd64

steps:
  - name: run-hello
    image: python:3.11
    commands:
      - echo "Running hello.py from repo..."
      - python hello.py
