kind: pipeline
type: docker
name: default


steps:
  - name: run-cloudflare-script
    image: python:3.9
    environment:
      API_TOKEN:
        from_secret: API_TOKEN
      SLACK_BOT_TOKEN:
        from_secret: SLACK_BOT_TOKEN
    commands:
      - pip install requests
      - python CloudFlare_Stats_To_Slack.py
