kind: pipeline
type: docker
name: cloudflare-stats

platform:
  os: linux
  arch: arm64

steps:
  - name: decompress-and-convert
    image: python:3.9
    volumes:
      - name: output-files
        path: /output-files
    commands:
      - python -V
      - pip install zstandard
      - ls -la
      - python zstd_to_csv_converter.py | tee /output-files/script.log
      - echo "✅ Script completed. Moving CSVs to /output-files..."
      - mv *.csv /output-files/
      - ls -lh /output-files/

volumes:
  - name: output-files
    host:
      path: /home/ubuntu/drone-ci/output

      
