kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: decompress-and-convert
    image: python:3.9
    volumes:
      - name: output-files
        path: /output-files
    commands:
      - python -V
      - pip install zstandard
      - ls -la
      - python zstd_to_csv_converter.py | tee /output-files/script.log
      - echo "✅ Script completed. Moving CSVs to /output-files..."
      - mv *.csv /output-files/
      - ls -lh /output-files/

  - name: send-logs-to-slack
    image: appleboy/slack-action
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: mc-poc
      username: DroneCI
      text: |
        Build completed. See attached script logs.
      attachments:
        - title: "Script Logs"
          text: |
            $(cat /output-files/script.log)

volumes:
  - name: output-files
    host:
      path: /Users/dhanasekar.kr/drone-ci/Output Files
