kind: pipeline
type: docker
name: test-secret

platform:
  os: linux
  arch: amd64

steps:
  - name: test-env
    image: python:3.10
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - echo "Checking if secret is available..."
      - bash -c 'echo "Token length: ${#GITHUB_TOKEN}"'
      - bash -c 'echo "Starts with: ${GITHUB_TOKEN:0:4}"'

# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: amd64

# # steps:
# #   - name: run python script
# #     image: python:3.10
# #     commands:
# #       - python hello.py

# steps:
#   - name: convert-only
#     image: python:3.10
#     commands:
#       - pip install zstandard
#       - python3 "ZSTD to CSV Converter.py"

# # steps:
# #   - name: convert-and-push
# #     image: python:3.10
# #     environment:
# #       GIT_AUTHOR_NAME: Drone CI Bot
# #       GIT_AUTHOR_EMAIL: ci-bot@example.com
# #       GIT_COMMITTER_NAME: Drone CI Bot
# #       GIT_COMMITTER_EMAIL: ci-bot@example.com
# #       GITHUB_TOKEN:
# #         from_secret: GITHUB_TOKEN
# #     commands:
# #       - pip install zstandard
# #       - python3 "ZSTD to CSV Converter.py"
