kind: pipeline
type: docker
name: test-secret

platform:
  os: linux
  arch: amd64

steps:
  - name: test-env
    image: bash
    environment:
      GITHUB_TOKEN: 
        from_secret: GITHUB_TOKEN
    commands:
      - echo "Checking if GITHUB_TOKEN is set..."
      - echo "Token length: ${#GITHUB_TOKEN}"
      - echo "Starts with: ${GITHUB_TOKEN:0:4}"

secrets:
  - name: GITHUB_TOKEN
