kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: run-cloudflare-script
    image: python:3.9
    environment:
      API_TOKEN:
        from_secret: API_TOKEN
      SLACK_BOT_TOKEN:
        from_secret: SLACK_BOT_TOKEN
    commands:
      - pip install boto3 pandas requests
      - python CloudFlare_Stats_To_Slack.py
