kind: pipeline
type: docker
name: hello-py

steps:
  - name: run-hello
    image: python:3.11
    commands:
      - echo "Running hello.py"
      - python -c "for i in range(30): print(f'Run {i+1}: Hello from Drone CI!')"
