kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:3.9
    commands:
      - python -V
      - python hello.py
      - echo "Starting resource-intensive task"
      - python -c "import time; [x**2 for x in range(10000000)]; time.sleep(5); print('Task completed')"
      
trigger:
  event:
    - push
