kind: pipeline
type: docker
name: default

steps:
  - name: decompress-and-convert
    image: python:3.9
    commands:
      - python -V
      - pip install zstandard
      - python zstd_to_csv_converter.py

trigger:
  event:
    - push
