kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: decompress-and-convert
    image: python:3.9
    commands:
      - python -V
      - pip install zstandard
      - ls -la 
      - python zstd_to_csv_converter.py

trigger:
  event:
    - push
