kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: decompress-and-convert
    image: python:3.9
    volumes:
      - name: output-files
        path: /output-files
    commands:
      - python -V
      - pip install zstandard
      - ls -la
      - python zstd_to_csv_converter.py
      - echo "✅ Script completed. Moving CSVs to /output-files..."
      - mv *.csv /output-files/
      - ls -lh /output-files/

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: mc-poc

volumes:
  - name: output-files
    host:
      path: /Users/dhanasekar.kr/drone-ci/Output Files
