kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: decompress-and-convert
    image: python:3.9
    volumes:
      - name: output-files
        path: /output-files
    commands:
      - python -V
      - pip install zstandard
      - ls -la
      - python zstd_to_csv_converter.py | tee /output-files/script.log
      - echo "✅ Script completed. Moving CSVs to /output-files..."
      - mv *.csv /output-files/
      - ls -lh /output-files/

  - name: send-notification-to-slack
    image: plugins/slack
    settings:
      token:
        env :
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      channel: mc-poc
      username: DroneCI
      template: |
        ✅ Build completed successfully!
        Repository: {{repo.name}}
        Branch: {{build.target}}
        Commit: {{build.commit}}
        Build Link: {{build.link}}

volumes:
  - name: output-files
    host:
      path: /Users/dhanasekar.kr/drone-ci/Output Files
