kind: pipeline
type: docker
name: test-secret

platform:
  os: linux
  arch: amd64

steps:
  - name: test-env
    image: bash
    commands:
      - echo "Checking if GITHUB_TOKEN is set..."
      - "bash -c 'echo \"Token length: ${#DRONE_SECRET_GITHUB_TOKEN}\"'"
      - "bash -c 'echo \"Starts with: ${DRONE_SECRET_GITHUB_TOKEN:0:4}\"'"
