kind: pipeline
type: docker
name: run-zstd-converter

platform:
  os: linux
  arch: amd64

steps:
  - name: run-zstd-to-csv
    image: python:3.11
    commands:
      - pip install zstandard
      - echo "Running ZSTD to CSV Converter"
      - python zstd_to_csv_converter.py